Chrystoki2 = {
    LibUNIX = {{ .HSMLibraryPath }}/libs/64/libCryptoki2.so;
    LibUNIX64 = {{ .HSMLibraryPath }}/libs/64/libCryptoki2.so;
}

Luna = {
  DefaultTimeOut = 500000;
  PEDTimeout1 = 100000;
  PEDTimeout2 = 200000;
  PEDTimeout3 = 10000;
  KeypairGenTimeOut = 2700000;
  CloningCommandTimeOut = 300000;
  CommandTimeOutPedSet = 720000;
}

CardReader = {
  RemoteCommand = 1;
}

Misc = {
   PE1746Enabled = 0;
   ProtectedAuthenticationPathFlagStatus = 0;
}

LunaSA Client = {
   ReceiveTimeout = 20000;
   SSLConfigFile = /usr/local/luna/openssl.cnf;
   ClientPrivKeyFile = {{ .HSMLibraryPath }}/config/certs/{{ .HSMClientAddress }}Key.pem;
   ClientCertFile = {{ ..HSMLibraryPath }}/config/certs/{{ .HSMClientAddress }}.pem;
   ServerCAFile = {{ ..HSMLibraryPath }}/config/certs/{{ .HSMIPAddress }}Cert.pem;
   NetClient = 1;
   TCPKeepAlive = 1;
   EnableTLS1_2 = 1;
   ServerName00 = {{ .HSMIPAddress }};
   ServerPort00 = 1792;
   ServerHtl00 = 0;
}
